#!/usr/bin/env bash
# relock-plugins.sh — cascade uv.lock refresh across all zkm plugins.
#
# WHY: every plugin pins the parent `zkm` package as an editable dep
# (`source = { editable = "../../" }`), so its uv.lock embeds zkm's version.
# When the parent zkm version bumps, EVERY plugin's uv.lock goes stale and must
# be re-locked. If the bump commit doesn't cascade, the plugin locks drift
# silently across versions (0.14 / 0.15 / 0.16 ...) and surface later as a dirty
# ` M uv.lock` that blocks the relay pool. This script is the cascade: it
# re-locks every plugin and commits the (1-line) version-pin refresh, so a
# parent bump never leaves plugin locks behind. (CLAUDE.md "zkm cascade" rule;
# dotclaude-skills TODO id:bae5 lever d.)
#
# Usage:
#   relock-plugins.sh           # relock + commit each plugin whose lock changed
#   relock-plugins.sh --check   # report stale plugins only; NO changes; exit 1 if any stale
#   relock-plugins.sh --push    # relock + commit + push each changed plugin (ff-only)
#
# Env:
#   ZKM_ROOT   parent zkm checkout (default: the repo this script lives in)
set -euo pipefail

ZKM_ROOT="${ZKM_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
PLUGINS_DIR="$ZKM_ROOT/plugins"
PARENT_VER="$(grep -m1 '^version' "$ZKM_ROOT/pyproject.toml" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' || true)"
[[ -n "$PARENT_VER" ]] || { echo "relock-plugins.sh: cannot read parent zkm version from $ZKM_ROOT/pyproject.toml" >&2; exit 2; }

MODE="apply"   # apply | check | push | install-hook
case "${1:-}" in
  --check)        MODE="check" ;;
  --push)         MODE="push" ;;
  --install-hook) MODE="install-hook" ;;
  "")             MODE="apply" ;;
  *) echo "relock-plugins.sh: unknown arg '$1' (use --check, --push, or --install-hook)" >&2; exit 2 ;;
esac

if [[ "$MODE" == "install-hook" ]]; then
  # Symlink the tracked guard into .git/hooks (preserves any other existing hooks,
  # unlike switching core.hooksPath). Idempotent.
  hookdir="$(git -C "$ZKM_ROOT" rev-parse --absolute-git-dir)/hooks"
  mkdir -p "$hookdir"
  ln -sf ../../scripts/hooks/pre-push "$hookdir/pre-push"
  echo "installed pre-push guard → $hookdir/pre-push"
  exit 0
fi

LOCK_PUSH="$HOME/.claude/skills/git-diary-workflow/git-lock-push.sh"
stale=()
changed=()
rc=0

for d in "$PLUGINS_DIR"/zkm-*/; do
  [[ -f "$d/uv.lock" ]] || continue
  name="$(basename "$d")"

  if [[ "$MODE" == "check" ]]; then
    # "Not synced" = EITHER the committed/working lock would change on relock
    # (`uv lock --check` exits 1) OR uv.lock has uncommitted changes (a fix that
    # was regenerated but never committed — the exact dirty-tree that blocks the
    # relay pool). NEVER writes the lockfile.
    reason=""
    ( cd "$d" && uv lock --check >/dev/null 2>&1 ) || reason="stale"
    if [[ -n "$(git -C "$d" status --porcelain -- uv.lock)" ]]; then
      reason="${reason:+$reason+}dirty"
    fi
    if [[ -n "$reason" ]]; then
      stale+=("$name($reason)")
      rc=1
    fi
    continue
  fi

  # apply / push: regenerate the lock in place.
  ( cd "$d" && uv lock >/dev/null 2>&1 ) || { echo "relock-plugins.sh: uv lock FAILED in $name" >&2; rc=1; continue; }

  # Only commit if the relock actually changed uv.lock (and ONLY uv.lock —
  # a relock must never sweep unrelated dirty paths into a chore commit).
  porcelain="$(git -C "$d" status --porcelain -- uv.lock)"
  [[ -n "$porcelain" ]] || continue

  git -C "$d" add uv.lock
  git -C "$d" commit -q -m "chore: refresh uv.lock — zkm ${PARENT_VER} cascade (id:bae5)

Cascade-relock after parent zkm bump to ${PARENT_VER}; plugin pins zkm as an
editable dep so the lock's version pin must follow. Generated by
scripts/relock-plugins.sh.

Co-Authored-By: Claude Opus 4.8 <noreply@anthropic.com>"
  changed+=("$name")

  if [[ "$MODE" == "push" ]]; then
    if [[ -x "$LOCK_PUSH" ]]; then
      ( cd "$d" && "$LOCK_PUSH" --ff-only ) || { echo "relock-plugins.sh: push FAILED in $name (left committed locally)" >&2; rc=1; }
    else
      git -C "$d" push --ff-only || { echo "relock-plugins.sh: push FAILED in $name (left committed locally)" >&2; rc=1; }
    fi
  fi
done

if [[ "$MODE" == "check" ]]; then
  if ((${#stale[@]})); then
    echo "STALE plugin uv.lock (parent zkm ${PARENT_VER}): ${stale[*]}" >&2
    echo "Run: $ZKM_ROOT/scripts/relock-plugins.sh --push" >&2
  else
    echo "all plugin uv.lock in sync with zkm ${PARENT_VER}"
  fi
  exit "$rc"
fi

if ((${#changed[@]})); then
  echo "relocked + committed (zkm ${PARENT_VER}): ${changed[*]}"
else
  echo "no plugin uv.lock needed a refresh (all in sync with zkm ${PARENT_VER})"
fi
exit "$rc"
